### ISSUE TITLE
ERROR: Is not a PostCSS plugin

### ISSUE THREAD

**Issue by arrterian** [gadyonysh/semantic-ui-less-module-loader#1]
Hello!

I installed this package and configured my webpack. But when I am running it I got error:

```
<text of semantic css>
is not a PostCSS plugin
        at Processor.normalize (/Users/roman/Projects/Project/node_modules/postcss/lib/processor.js:145:15)
        at new Processor (/Users/roman/Projects/Project/node_modules/postcss/lib/processor.js:51:25)
        at Object.postcss (/Users/roman/Projects/Project/node_modules/postcss/lib/postcss.js:73:10
```
"extract-text-webpack-plugin": "^1.0.1",
"webpack": "^1.14.0",

**Comment by gadyonysh** [comment]
@RomanValihura Could you provide your deps list from package.json and webpack config?
